"""
Playwright Script Mapper — Translates static analysis output to browser automation.

Converts InjectionPoint objects from Stage 1 into executable Playwright interaction
sequences, handling different parameter locations and content types.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from .models import ExploitTask, InjectionPoint, VulnType

logger = logging.getLogger(__name__)


class InteractionType(Enum):
    """Types of browser interactions."""
    NAVIGATE = "navigate"
    FILL = "fill"
    CLICK = "click"
    SELECT = "select"
    SUBMIT = "submit"
    WAIT = "wait"
    EVALUATE = "evaluate"
    SET_HEADER = "set_header"
    MODIFY_URL = "modify_url"


@dataclass
class PlaywrightAction:
    """Single Playwright action definition."""
    action_type: InteractionType
    selector: Optional[str] = None
    value: Optional[str] = None
    options: dict[str, Any] = field(default_factory=dict)
    
    def to_python_code(self) -> str:
        """Generate executable Python code for this action."""
        match self.action_type:
            case InteractionType.NAVIGATE:
                return f'await page.goto("{self.value}", wait_until="networkidle")'
            case InteractionType.FILL:
                return f'await page.fill("{self.selector}", """{self.value}""")'
            case InteractionType.CLICK:
                return f'await page.click("{self.selector}")'
            case InteractionType.SUBMIT:
                return f'await page.click("{self.selector or 'button[type=submit]'}")'
            case InteractionType.WAIT:
                wait_for = self.options.get("for", "load")
                timeout = self.options.get("timeout", 5000)
                return f'await page.wait_for_load_state("{wait_for}", timeout={timeout})'
            case InteractionType.SET_HEADER:
                return f'# Header set in context: {self.value}'
            case InteractionType.MODIFY_URL:
                return f'url = url.replace("{{{self.selector}}}", "{self.value}")'
            case _:
                return f'# TODO: Implement {self.action_type.value}'


@dataclass
class PlaywrightScript:
    """
    Complete Playwright script for vulnerability validation.
    
    Can be exported as executable Python code or JSON for remote execution.
    """
    script_id: str
    task_id: str
    actions: list[PlaywrightAction] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    
    def to_python_script(self) -> str:
        """Generate complete executable Python script."""
        lines = [
            "import asyncio",
            "from playwright.async_api import async_playwright",
            "",
            f"# Auto-generated Playwright script for vulnerability validation",
            f"# Task: {self.task_id}",
            f"# Generated by: Shannon Pro Dynamic Agent",
            "",
            "async def run_validation():",
            '    async with async_playwright() as p:',
            '        browser = await p.chromium.launch(headless=True)',
            '        context = await browser.new_context()',
            '        page = await context.new_page()',
            '',
        ]
        
        for i, action in enumerate(self.actions, 1):
            code = action.to_python_code()
            lines.append(f"        # Step {i}: {action.action_type.value}")
            lines.append(f"        {code}")
            lines.append("")
        
        lines.extend([
            '        # Collect evidence',
            '        screenshot_path = f"evidence_{int(asyncio.get_event_loop().time())}.png"',
            '        await page.screenshot(path=screenshot_path, full_page=True)',
            '        content = await page.content()',
            '        print(f"Page title: {await page.title()}")',
            '        print(f"Content length: {len(content)}")',
            '        print(f"Screenshot saved: {screenshot_path}")',
            '',
            '        await context.close()',
            '        await browser.close()',
            '',
            'if __name__ == "__main__":',
            '    asyncio.run(run_validation())',
        ])
        
        return "\n".join(lines)
    
    def to_json(self) -> str:
        """Serialize to JSON for API transmission."""
        return json.dumps({
            "script_id": self.script_id,
            "task_id": self.task_id,
            "actions": [
                {
                    "type": a.action_type.value,
                    "selector": a.selector,
                    "value": a.value,
                    "options": a.options,
                }
                for a in self.actions
            ],
            "metadata": self.metadata,
        }, indent=2)


class PlaywrightScriptMapper:
    """
    Maps static analysis InjectionPoints to executable Playwright scripts.
    
    Handles various parameter locations:
    - Query parameters: URL manipulation
    - Form fields: Input filling and form submission
    - Headers: Context-level header injection
    - Path parameters: URL template replacement
    - JSON body: API request construction
    """
    
    def map_task_to_script(self, task: ExploitTask) -> PlaywrightScript:
        """
        Convert ExploitTask to PlaywrightScript.
        
        Args:
            task: Exploit task with injection points and strategies
            
        Returns:
            PlaywrightScript ready for execution
        """
        script = PlaywrightScript(
            script_id=f"script-{task.task_id[:8]}",
            task_id=task.task_id,
            metadata={
                "vuln_type": task.vuln_type.value,
                "target_url": task.target_url,
                "target_method": task.target_method,
            },
        )
        
        # Add navigation action
        script.actions.append(PlaywrightAction(
            action_type=InteractionType.NAVIGATE,
            value=task.target_url,
        ))
        
        # Map each injection point to actions
        for injection_point in task.injection_points:
            actions = self._map_injection_point(injection_point, task)
            script.actions.extend(actions)
        
        # Add submission action
        script.actions.append(PlaywrightAction(
            action_type=InteractionType.SUBMIT,
            selector="button[type='submit']",
        ))
        
        # Add wait action
        script.actions.append(PlaywrightAction(
            action_type=InteractionType.WAIT,
            options={"for": "networkidle", "timeout": 10000},
        ))
        
        return script
    
    def _map_injection_point(
        self,
        injection_point: InjectionPoint,
        task: ExploitTask,
    ) -> list[PlaywrightAction]:
        """
        Map a single injection point to Playwright actions.
        
        Returns:
            List of actions to interact with this injection point
        """
        location = injection_point.parameter_location
        name = injection_point.parameter_name
        
        match location:
            case "query":
                return self._map_query_parameter(injection_point, task)
            case "body" | "form":
                return self._map_form_field(injection_point)
            case "header":
                return self._map_header_injection(injection_point)
            case "path":
                return self._map_path_parameter(injection_point, task)
            case "json":
                return self._map_json_body(injection_point, task)
            case "cookie":
                return self._map_cookie_injection(injection_point)
            case _:
                # Fallback: try to find input by name
                return self._map_form_field(injection_point)
    
    def _map_query_parameter(
        self,
        injection_point: InjectionPoint,
        task: ExploitTask,
    ) -> list[PlaywrightAction]:
        """Map query parameter to URL manipulation action."""
        # Build URL with parameter
        from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
        
        parsed = urlparse(task.target_url)
        params = parse_qs(parsed.query)
        params[injection_point.parameter_name] = [injection_point.current_value]
        new_query = urlencode(params, doseq=True)
        modified_url = urlunparse(parsed._replace(query=new_query))
        
        return [PlaywrightAction(
            action_type=InteractionType.MODIFY_URL,
            selector=injection_point.parameter_name,
            value=injection_point.current_value,
            options={"modified_url": modified_url},
        )]
    
    def _map_form_field(self, injection_point: InjectionPoint) -> list[PlaywrightAction]:
        """Map form field to fill action."""
        selectors = [
            f'input[name="{injection_point.parameter_name}"]',
            f'textarea[name="{injection_point.parameter_name}"]',
            f'select[name="{injection_point.parameter_name}"]',
            f'[id="{injection_point.parameter_name}"]',
            f'input[placeholder*="{injection_point.parameter_name}" i]',
        ]
        
        # Use first matching selector
        selector = selectors[0]
        
        return [PlaywrightAction(
            action_type=InteractionType.FILL,
            selector=selector,
            value=injection_point.current_value,
            options={"fallback_selectors": selectors[1:]},
        )]
    
    def _map_header_injection(
        self,
        injection_point: InjectionPoint,
    ) -> list[PlaywrightAction]:
        """Map header injection to context-level header setting."""
        return [PlaywrightAction(
            action_type=InteractionType.SET_HEADER,
            selector=injection_point.parameter_name,
            value=injection_point.current_value,
        )]
    
    def _map_path_parameter(
        self,
        injection_point: InjectionPoint,
        task: ExploitTask,
    ) -> list[PlaywrightAction]:
        """Map path parameter to URL template replacement."""
        return [PlaywrightAction(
            action_type=InteractionType.MODIFY_URL,
            selector=injection_point.parameter_name,
            value=injection_point.current_value,
        )]
    
    def _map_json_body(
        self,
        injection_point: InjectionPoint,
        task: ExploitTask,
    ) -> list[PlaywrightAction]:
        """Map JSON body parameter to API request via evaluate."""
        payload_json = json.dumps({injection_point.parameter_name: injection_point.current_value})
        
        return [PlaywrightAction(
            action_type=InteractionType.EVALUATE,
            value=payload_json,
            options={
                "url": task.target_url,
                "method": task.target_method,
            },
        )]
    
    def _map_cookie_injection(
        self,
        injection_point: InjectionPoint,
    ) -> list[PlaywrightAction]:
        """Map cookie injection to cookie setting."""
        return [PlaywrightAction(
            action_type=InteractionType.EVALUATE,
            value=f"document.cookie = '{injection_point.parameter_name}={injection_point.current_value}; path=/'",
        )]
    
    def apply_payload_to_script(
        self,
        script: PlaywrightScript,
        injection_point_id: str,
        payload: str,
    ) -> PlaywrightScript:
        """
        Create a copy of the script with a specific payload applied.
        
        Args:
            script: Base script to modify
            injection_point_id: ID of injection point to target
            payload: Payload string to inject
            
        Returns:
            New PlaywrightScript with payload applied
        """
        import copy
        new_script = copy.deepcopy(script)
        
        for action in new_script.actions:
            if action.selector == injection_point_id or \
               (action.options and action.options.get("target_param") == injection_point_id):
                action.value = payload
        
        return new_script
