from datetime import datetime

from core.skills.registry import tool

_severities = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "🔵"}

@tool()
def generate_report(
    findings: str,
    severity: str = "medium",
    title: str = "Security Audit Report",
    author: str = "OmniClaw"
) -> str:
    """Compile findings into a Markdown report with severity scores and evidence snippets."""
    lines = findings.strip().split("\n")
    severity_icon = _severities.get(severity.lower(), "⚪")
    total = len([x for x in lines if x.strip()])
    report = f"""# {title}

**Author:** {author}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
**Severity:** {severity_icon} {severity.upper()}
**Total Findings:** {total}

---
"""
    section_count = 0
    current_section = "General"
    snippets = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("=== ") and stripped.endswith(" ==="):
            current_section = stripped.strip("= ")
            section_count += 1
            report += f"\n## {section_count}. {current_section}\n\n"
            continue
        if stripped.startswith("! ") or stripped.startswith("[!]") or stripped.startswith("[~]"):
            report += f"- **{stripped[2:].strip()}**\n"
            snippets.append(stripped)
        elif stripped.startswith("  "):
            report += f"  - `{stripped.strip()}`\n"
        else:
            report += f"- {stripped}\n"
    report += f"""

---
### Evidence Snippets ({len(snippets)})

"""
    for i, s in enumerate(snippets[:20], 1):
        report += f"{i}. `{s[:150]}`\n"
    if len(snippets) > 20:
        report += f"\n*... and {len(snippets) - 20} more snippets*"
    report += f"""

---
### Severity Legend
| Level | Icon | Description |
|-------|------|-------------|
| Critical | {_severities['critical']} | Immediate exploitation possible, no prerequisites |
| High | {_severities['high']} | Exploitation possible with some conditions |
| Medium | {_severities['medium']} | Limited impact or requires user interaction |
| Low | {_severities['low']} | Minor issue, defense-in-depth |
| Info | {_severities['info']} | Informational, no direct risk |

---
*Report generated by OmniClaw Security Audit Toolchain*
"""
    return report


@tool()
def generate_finding_summary(findings_text: str) -> str:
    """Produce a compact one-line summary per finding with severity tag."""
    import re
    lines = findings_text.strip().split("\n")
    summaries = []
    severity_pattern = re.compile(r"\b(critical|high|medium|low|info)\b", re.IGNORECASE)
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        severity = "info"
        match = severity_pattern.search(stripped)
        if match:
            severity = match.group(1).lower()
        icon = _severities.get(severity, "⚪")
        short = stripped[:100]
        if stripped.startswith("=== ") or stripped.startswith("#"):
            continue
        summaries.append(f"{icon} [{severity.upper()}] {short}")
    if not summaries:
        return "No findings to summarize."
    result = f"=== Finding Summary ({len(summaries)} items) ===\n"
    result += "\n".join(summaries)
    return result


@tool()
def export_to_json(markdown_report: str, output_path: str = "") -> str:
    """Convert a Markdown report to JSON and optionally save to a file."""
    import json
    import re
    items = []
    current_title = ""
    for line in markdown_report.split("\n"):
        if line.startswith("## "):
            current_title = line.strip("# ")
        elif line.startswith("- **"):
            match = re.match(r"- \*\*(.+?)\*\*", line)
            if match:
                items.append({"section": current_title, "finding": match.group(1).strip(), "detail": line.strip()})
    result = json.dumps({"findings": items, "count": len(items), "generated": datetime.now().isoformat()}, indent=2)
    if output_path:
        with open(output_path, "w") as f:
            f.write(result)
        return f"Exported {len(items)} findings to {output_path}"
    return result
